"""POST /api/vehicle-report/{id} — assemble the buyer-facing report payload.

The Flutter client renders this into a PDF. Reuses the ownership guard and the
prediction engine; the payload is everything the report needs in one call.
"""
import logging
from datetime import datetime, timedelta, timezone

from fastapi import APIRouter, Depends

from ..data import DataAccess, get_data
from ..predict.engine import predict, row_to_response, to_db_row
from ..rate_limit import rate_limit
from ..security import CurrentUser

logger = logging.getLogger("fixora.report")
router = APIRouter()

CACHE_TTL = timedelta(hours=24)

DISCLAIMER = (
    "This report is an informative estimate generated by Fixora using the "
    "vehicle's recorded service history, age, mileage and maintenance patterns. "
    "It is NOT a certified valuation or a substitute for a professional "
    "mechanical inspection. Figures are indicative and in Sri Lankan Rupees (LKR)."
)


def _is_fresh(generated_at) -> bool:
    try:
        ts = datetime.fromisoformat(str(generated_at).replace("Z", "+00:00"))
        if ts.tzinfo is None:
            ts = ts.replace(tzinfo=timezone.utc)
        return datetime.now(timezone.utc) - ts < CACHE_TTL
    except (ValueError, TypeError):
        return False


def _prediction(data: DataAccess, vehicle: dict) -> dict:
    recent = data.get_recent_valuation(vehicle["id"])
    if recent and _is_fresh(recent.get("generated_at")):
        return row_to_response(recent)

    records = data.get_service_records(vehicle["id"])
    baseline_row = None
    if vehicle.get("make_id") and vehicle.get("model_id") and vehicle.get("year_of_manufacture"):
        baseline_row = data.get_market_baseline(
            vehicle["make_id"], vehicle["model_id"], vehicle["year_of_manufacture"]
        )
    result = predict(vehicle, records, baseline_row)
    try:
        data.save_valuation(to_db_row(result))
    except Exception:
        logger.exception("Could not cache valuation for report")
    return result


@router.post("/api/vehicle-report/{vehicle_id}")
def vehicle_report(
    vehicle_id: str,
    user: CurrentUser = Depends(rate_limit),
    data: DataAccess = Depends(get_data),
):
    vehicle = data.require_owned_vehicle(vehicle_id, user.id)  # 403 / 404
    pred = _prediction(data, vehicle)
    history = data.get_service_history_detailed(vehicle_id)

    service_history = [
        {
            "date": str(r.get("serviced_at") or "")[:10],
            "work": r.get("work_performed"),
            "inspection": r.get("inspection_notes"),
            "severity": r.get("severity"),
            "odometer": r.get("odometer_reading"),
            "mechanic": (r.get("employees") or {}).get("full_name"),
            "labour_cost": r.get("labour_cost"),
            "parts": [
                {"name": p.get("part_name"), "qty": p.get("quantity")}
                for p in (r.get("service_parts") or [])
            ],
        }
        for r in history
    ]

    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "station": {"name": "Fixora Service Center"},
        "vehicle": {
            "registration": vehicle.get("registration_number"),
            "make": (vehicle.get("make") or {}).get("name"),
            "model": (vehicle.get("model") or {}).get("name"),
            "year": vehicle.get("year_of_manufacture"),
            "engine": vehicle.get("engine_type"),
            "transmission": vehicle.get("transmission"),
            "mileage": vehicle.get("current_mileage"),
        },
        "condition": pred["condition"],
        "subsystems": pred["subsystems"],
        "value": pred["value"],
        "insights": pred["insights"],
        "recommendations": pred["recommendations"],
        "llm_factors": pred["llm_factors"],
        "service_history": service_history,
        "disclaimer": DISCLAIMER,
    }
